name: Update repository
on:
  push:
    paths:
      - "src/**"
      - "README.md"

jobs:
  update-repo:
    name: Update repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Update documentation
        run: npm run docs:gen

      - name: Commit documentation changes
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
          message: "[auto] Update docs"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update source code
        run: npm run lint

      - name: Commit source changes
        uses: EndBug/add-and-commit@v4
        with:
          add: src
          message: "[auto] Lint source code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
